#ifndef FFFTPGUI_UI_OPTION_FIREWALLDATATRANSCEIVER_HPP_
#define FFFTPGUI_UI_OPTION_FIREWALLDATATRANSCEIVER_HPP_

#include "ui/base/formdatatransceiver.hpp"
#include "optionfirewallform.hpp"

DECL_DATATRANSCEIVER(OptionFirewallForm);

#endif  // FFFTPGUI_UI_OPTION_FIREWALLDATATRANSCEIVER_HPP_
