#ifndef FFFTPGUI_UI_OPTION_MIRRORINGDATATRANSCEIVER_HPP_
#define FFFTPGUI_UI_OPTION_MIRRORINGDATATRANSCEIVER_HPP_

#include "ui/base/formdatatransceiver.hpp"
#include "optionmirroringform.hpp"

DECL_DATATRANSCEIVER(OptionMirroringForm);

#endif  // FFFTPGUI_UI_OPTION_MIRRORINGDATATRANSCEIVER_HPP_
