#ifndef FFFTPGUI_UI_OPTION_TRANSFER3DATATRANSCEIVER_HPP_
#define FFFTPGUI_UI_OPTION_TRANSFER3DATATRANSCEIVER_HPP_

#include "ui/base/formdatatransceiver.hpp"
#include "optiontransfer3form.hpp"

DECL_DATATRANSCEIVER(OptionTransfer3Form);

#endif  // FFFTPGUI_UI_OPTION_TRANSFER3DATATRANSCEIVER_HPP_
