#ifndef FFFTPGUI_UI_OPTION_VIEW2DATATRANSCEIVER_HPP_
#define FFFTPGUI_UI_OPTION_VIEW2DATATRANSCEIVER_HPP_

#include "ui/base/formdatatransceiver.hpp"
#include "optionview2form.hpp"

DECL_DATATRANSCEIVER(OptionView2Form);

#endif  // FFFTPGUI_UI_OPTION_VIEW2DATATRANSCEIVER_HPP_
